### ISSUE TITLE
Certain apps don't get restored  

### ISSUE THREAD

**Issue by pablorodriguezzurro** [kangyu-california/PersistentWindows#56] opened 2020-10-30 11:21 UTC
Some Apps like Spotify, Dashlane, Windows File Explorer, etc. refuse to be restored properly after disconnecting one monitor or after awake the PC. 

PD: Thank you very much for your effort in this amazing tool! :smiley:

**Comment by JohnChristmann** [comment] 2020-10-30 18:49
To add some others: Winamp (5.xx) does not move at all, and the Windows Settings app gets restored to an incorrect position and size.  I personally have had not had any issues with explorer windows.

**Comment by morrisonbrett** [comment] 2020-10-30 19:25
> To add some others: Winamp (5.xx)....

I love that you're using WinAmp! #LLama

**Comment by kangyu-california** [comment] 2020-10-30 21:48
@JohnChristmann 
Certain window apps (task manager, settings etc) requires running PW with elevated privilege (administrator) to restore.
This is documented in "tips for power users" section of readme

**Comment by JohnChristmann** [comment] 2020-10-30 21:56
@kangyu-california I am running it with administrative privileges.  It still seems to screw up the Settings app nearly every time (though not every time.)

**Comment by pablorodriguezzurro** [comment] 2020-10-30 22:21
@kangyu-california @JohnChristmann 

It is runing with highest privileges in the unique administrator account. The confirmed apps that don't restore 100% of the times to my machine are: 

- Windows Explorer
- Telegram Web
- GoG Galaxy 2.0 
- Dashlane
- Spotify (UWP)
- Outlook (Office 365)

Some others fail too sometimes but I have not tracked them exhaustively. 

My OS is Windows 10 Pro Version	10.0.19041 Build 19041

**Comment by kangyu-california** [comment] 2020-11-12 05:18
I found a windows 10 bug when using windows 10 snap assistance to place ANY window to 2x2 snap position (along screen edge), if the snap edge is adjacent to another screen, windows 10 would place the window several pixels across the screen boundary, effectively making the window stride across 2 monitors, 

The overstretch issue is barely visible, but can be verified using spyxx tool from visual studio or by examine the screen coordinate from dumped db file.

The thing is whenever this happens, the window will be restored to wrong position and wrong size, although all the coordinates passed to MoveWIndows() API is accurate. I would deem this as a Microsoft implementation bug.

The workaround is to avoid snapping window to those adjacent locations, if the window is fully contained within ONE monitor,PersistentWindows seems to working fine.

**Comment by JohnChristmann** [comment] 2020-11-12 16:02
That might explain why my main Steam window always ends up 1 pixel onto the second monitor (I keep it docked to the right side of the left monitor.)  I also keep Winamp snapped to a screen corner, but I believe it uses its own snapping system and Persistent Windows seems to ignore the program entirely.

**Comment by kangyu-california** [comment] 2020-11-16 07:13
Pre-release 5.5 fixes over-snapped window by trimming off the overlap area, so the restored window will be several pixel away from screen edge, while keeping the coordinate of top-left corner unchanged.

As for winamp, it is a different story, the visual part is a child window instead of top level window. and MoveWindow() API has no effect on child window. I will try to come up with a fix (which will address #issue 59 at the same time) in later releases.

**Comment by garyd9** [comment] 2021-01-04 00:25
I'd love to re-open this, as I experienced the same issue with a different app (hwinfo64), but I've tracked it down to a bug in the code and a misunderstanding over "parent" vs "owner" relationships of windows.   If the following conditional is removed from CaptureWindowsOfInterest(), it appears to work:

if (User32.GetParent(y) != IntPtr.Zero)
   continue;
   
Why?  Because an app can create a top level invisible frame, and then create another window that's OWNED by that top level window.  By definition, a window that has an OWNER cannot also have a parent (It's either/or when calling CreateWindowEx().)  The result is a window on the desktop that has no parent, but does have an owner. 

Perhaps an alternative and more surefire way to validate is to validate that the parentless window also has WS_EX_APPWINDOW set, but I wouldn't bother with that.  (APPWINDOW is only used to force the window to show in the taskbar.)

**Comment by garyd9** [comment] 2021-01-04 01:06
Okay, perhaps this might be a better solution:

There are two places where the above GetParent() check is done.  GetParent() will return a parent OR an owner (but doesn't let you know which one.)  In the case of hwinfo64 that I'm testing with, it returns the owner (because it has no parent.)  Therefore, it's != 0, and as a result, it's not included in the list of windows stored.

There IS a way to determine if a window is virtually parented by the desktop (without ownership interfering.)   GetAncestor() can be called with GA_PARENT (1) to reveal ONLY a parent (not owner) and if the window is parentless, it returns the desktop (GetDesktop())

Give me a couple hours and I'll send a pull req....

**Comment by garyd9** [comment] 2021-01-04 01:30
PR sent.

**Comment by garyd9** [comment] 2021-01-04 01:41
Well, damn.  It seems to properly save the window data now, but doesn't restore it properly.  Hrm.  I probably won't have time to get back into that code until next weekend. :(

**Comment by garyd9** [comment] 2021-01-04 02:28
disregard my comment saying that my PR didn't work properly.  It did work fine, but ran into operator error.  (see my edited previous comment.)

**Comment by garyd9** [comment] 2021-01-06 17:38
Been running with the above (and now merged) PR for a few days with no issues.  I'll need to pay attention to when the merge is built into a release to watch for reports from other users using other apps.

**Comment by JohnChristmann** [comment] 2021-01-06 23:36
I'll try this code out and see if it helps with Winamp.

**Comment by garyd9** [comment] 2021-01-09 21:49
> I'll try this code out and see if it helps with Winamp.

Any news?

**Comment by JohnChristmann** [comment] 2021-01-10 03:01
Ah sorry I was going to update this but it slipped my mind.  This change does not affect Winamp.  As per earlier discussion, Winamp apparently uses child windows for all visible program windows, and Persistent Windows currently only captures the invisible main window.

**Comment by kangyu-california** [comment] 2021-02-16 05:24
winamp window restore is supported in release 5.16

**Closed by kangyu-california** 2021-02-16 05:24 UTC

**Comment by JohnChristmann** [comment] 2021-02-18 15:33
Winamp support is not working on my system.  Persistent Windows does not attempt to restore any of Winamp's windows.

**Comment by kangyu-california** [comment] 2021-03-01 00:22
@JohnChristmann 
Could not reproduce what you said, please retest with latest 5.18 release.
Thanks!

**Comment by JohnChristmann** [comment] 2021-03-02 16:51
Still no change with 5.18.  I wonder if there are some differences with the way Winamp handles windowing with different versions and/or skin types?  I'm using Winamp 5.8 with a modern skin that utilizes multiple windows currently.

**Comment by kangyu-california** [comment] 2021-03-08 01:01
@JohnChristmann 
Try 5.19
It is known that Winamp may move by itself (not controlled by PW)
You may disable auto restore of winamp window by Ctrl+Shift moving it to verify.

**Comment by JohnChristmann** [comment] 2021-03-11 16:29
Well I haven't noticed any changes in 5.19.  Winamp either stays where it is or moves (seems random, and same behavior as always) and Persistent Windows never affects it.  I wonder if trying to support Winamp is a lost cause?

**Comment by kangyu-california** [comment] 2021-03-12 00:01
@JohnChristmann We have proved the "random" moving of Winamp window is not caused by PW. So the issue should really go to Winamp developer.

There is a perfect example in #92 to explain why PW should not intervene window move on its own will

**Comment by kangyu-california** [comment] 2021-03-12 00:06
@JohnChristmann  For workaround, you may restore window layout to a previously captured snapshot. It is just one mouse click away.

**Comment by JohnChristmann** [comment] 2021-03-12 01:49
@kangyu-california I'll give that a try, thanks.  I think I'll also mention it to the WACUP developer (community update project for Winamp, since Winamp is no longer officially developed.)
