### ISSUE TITLE
How to stop: Splash window will pop up

### ISSUE THREAD

**Issue by Fite4k** [kangyu-california/PersistentWindows#24] opened 2020-07-04 15:58 UTC
Is it possible to stop this? : Run PersistentWindows.exe as normal user, a splash window will pop up, indicating the program has started successfully.

The program is awesome, but I really don´t need the pop up :)

**Comment by kangyu-california** [comment] 2020-07-04 19:04
This is duplicate of  issue 10.
https://github.com/kangyu-california/PersistentWindows/issues/10

Please run "PersistentWindows.exe -silent" to suppress the splash window at startup.

**Closed by kangyu-california** 2020-07-04 19:04 UTC
