### ISSUE TITLE
Window flickering and prolonged inaccessibility after screens turn back on

### ISSUE THREAD

**Issue by Steve06** [kangyu-california/PersistentWindows#109] opened 2021-04-27 10:19 UTC
In a dual monitor setup (both attached via DisplayPort) running the latest Windows 10 version and PersistentWindows 5.21, when the screens turn back after some idle time, it can take a good 10 seconds (with the system tray logo turning red) for the computer to become fully accessible again as it restores my 10-15 windows that are typically open, with individual windows flickering as it seems that they are being moved repeatedly back and forth between background and foreground coming to a halt. No user input is advisable during this time as it seems to further delay the process.
Although the PC is older, it is still fast enough for comfortable office work and some games with its Intel i7-3770 CPU @ 3.40GHz, 16 GB RAM and Intel SSDs.
PersistentWindows is being started via the Task Scheduler and the parameters "-splash=0 -fix_zorder=1".

Is such a waiting of about 5-10 seconds normal before we can resume work running PersistentWindows? And isn't there a bug or inefficiency in the code if some windows seem to be moved back and forth repeatedly?

**Comment by kangyu-california** [comment] 2021-04-27 16:26
Zorder restore feature is still in development.

Microsoft provide two APIs to adjust zorder, I have tried both of them but so far still unable to find a silver bullet to restore zorder in one pass.

Currently PW calls two APIs in interleaving style in multiple passes to guarantee success, with runtime sacrificed.

In next release a new command option will be available to customize the steategy of restore zorder. User will have option to improve run time, with accuracy compromised however.

**Comment by Steve06** [comment] 2021-04-27 17:15
Thank you, so maybe we could also get an additional option to ignore z-order of windows altogether, i.e., make no attempt at restoring z-order ? In my use case, I'm mainly concerned about x,y positioning.
I'm not sure if such an option is already implemented, I just skimmed over the current parameter list and couldn't find it.

**Comment by kangyu-california** [comment] 2021-04-27 17:24
Just remove -fix_order=1 from command line will ignore zorder, which is the default behavior

**Comment by Steve06** [comment] 2021-05-03 12:47
Yes, I realized that this is the best solution for me for the time being. The runtime is much better now. Thanks.
I read Microsoft will address the overall issue in a Windows 10 update expected by the end of the year. Curious to see how well that will work.

**Comment by kangyu-california** [comment] 2021-05-05 22:33
From the early feedback of insider preview user, it seems the issue is not resolved yet.
I wish MSFT could take away the algorithm from this project and build into Windows10.

**Comment by kangyu-california** [comment] 2021-05-09 23:14
The prolonged window flickering issue has been addressed in release 5.22, when -fix_zorder=1 is turned on or when restore snapshot.

**Closed by kangyu-california** 2021-05-09 23:14 UTC
