### ISSUE TITLE
Minimized windows keep popping back up

### ISSUE THREAD

**Issue by Adambean** [kangyu-california/PersistentWindows#29] opened 2020-08-04 14:49 UTC
Hi there,

I started using your fork of PersistentWindows (v4.3.0) as of yesterday. I hadn't realised it existed. -- Thanks for continuing work on this utility.

I've noticed an issue vs the original whereby when you minimize a window this utility will cause it to reappear within a second unless you pause auto-restore. It also happens when you ALT+TAB to different applications. This likely shouldn't be the case if the user explicitly decides to minimize a window. -- A particularly regular cause is resuming a session after a lock or screensaver.

I did pause auto-restore for a while, but at a later point when you want to resume it to correct resolution and monitor power changes (because that's the whole point of the utility) it'll resume opening up minimized windows.

**Comment by kangyu-california** [comment] 2020-08-04 23:36
Hi,

Thanks for trying out PersistentWindows.

The incorrect restore of minimized window issue seems to be a random one on my side, it will take me some time to find a way to reproduce it consistently. It would be very helpful if you can provide more information about the issue, such as the name of  application that got incorrectly restored; Are you Alt+Tab from a full screen video game? Because only in that scenario a display setting change event will be triggered to restore previous window layout (before launching the video game)

Another point is that It usually takes 3 ~ 6 seconds for PersistenWindows to capture window move/maximize/minimize/snap event, so you need to wait for that long before switching display or let system sleep.

Also it take 10 ~ 20 seconds for PersistentWindows to fully restore window position. It is recommended to not perform any window move operation during that period, as PersistentWindows is competing with Windows OS to have a finaly say of window position. Any user move during that period will be reverted. It might be helpful to run PersistentWindows.exe with "-notification_on" command option to get some visual hint during restore.

I will create a new release 4.32 as early as 8/8 to address this issue.

Thanks for the feedback

**Comment by Adambean** [comment] 2020-08-05 10:02
Thanks for your swift response.

I can appreciate the randomness of this. :) This impacts both my home PC and office PC (currently using the latter over VPN+RDP) almost the same. Both PCs have some common applications such as Google Chrome, Mozilla Thunderbird, Sublime Text 3, and ConsoleZ.

The times you mentioned make sense. -- When I return from a lunch break unlocking either PC causes a full restore, and seems to stick there as per the issue description, though if I leave it to settle for a minute it does calm down. What you've said does explain why this can (and may need to) happen. Resuming a session from the Windows lock screen when a screensaver has happened seems to be the primary scenario, both in a console session and RDP.

I'll close down PersistentWindows and add `-notification_on` to its launch parameters. They definitely seem to be appearing:

![image](https://user-images.githubusercontent.com/1108717/89399896-05caa480-d70b-11ea-8967-147a2adfc554.png)

**Comment by kangyu-california** [comment] 2020-08-08 15:49
Hi,

Version 4.32 is released, please try.

**Comment by Adambean** [comment] 2020-08-08 16:26
Thanks, I'll try that today. I updated to 4.31 literally an hour ago. :)

**Comment by kangyu-california** [comment] 2020-08-08 23:21
Hi,

Just released 4.33 to fix a related issue :)

**Comment by kangyu-california** [comment] 2020-08-16 00:28
The issue is fully resolved by version 4.34

**Closed by kangyu-california** 2020-08-16 00:28 UTC

**Comment by Adambean** [comment] 2020-08-17 09:25
Thanks for the update, I'll try this out today.

**Comment by Adambean** [comment] 2020-09-01 14:37
I wouldn't say this is resolved. There is still a noticeable delay after unlocking the workstation before I can continue working because this utility is forcing with a giant iron hammer what is on screen. Furthermore quite often when moving an existing window intentionally this utility is pulling it back to where it was long after unlocking the workstation.

(I've stopped using this utility for the time being as it's blocking work.)

**Comment by kangyu-california** [comment] 2020-09-01 18:10
Thanks for your help.
The tool would not be able to achieve current status without user's feedback.

**Comment by Adambean** [comment] 2020-09-01 19:59
_(Sorry if I sounded rather negative there. Nothing personal intended.)_

**Comment by kangyu-california** [comment] 2020-09-01 22:16
I know there are some lighter workarounds available either by tweaking registry or uninstall unused monitor driver, but the true problem is how to let Windows OS save multiple display configs and dynamically switching between them. This is a heavy problem by nature, thus requiring a heavy solution like PersistentWindows.

**Comment by kangyu-california** [comment] 2020-10-29 05:22
Hi

You may try latest release 5.0 with snapshot feature which can be used to address slow RDP session recovery issue.

The idea is to let PersistentWindows (PW) work in semi-automatic way, here is my suggestion
1. pause PW auto restore
2. take a snapshot by double click PW icon at any time
3. disconnect RDP session
4. reconnect RDP session, OS will misplace windows around.
5. restore previous snapshot by (single) click PW icon, the recovery process should be fairly quick without interference from OS.

Hope this helps.
