### ISSUE TITLE
KakaoTalk gets reset to main monitor

### ISSUE THREAD

**Issue by GloriousGloryGG** [kangyu-california/PersistentWindows#96] opened 2021-03-11 16:44 UTC
With persistent windows running it constantly resets the KakaoTalk main window on the main monitor.  When I shut the program down no issues.

**Comment by kangyu-california** [comment] 2021-03-11 23:55
Not getting enough details about how to reproduce the issue (check out the last section of Readme), anyway I really don't want to install and register another social media App.

My guess is this is similar to issue #90 #92, You may prevent PW from restoring Kakao Talk window by Ctrl+Shift moving it.
This workaround is available since release 5.19

Good luck.

**Closed by kangyu-california** 2021-03-11 23:55 UTC
