### ISSUE TITLE
Detected as virus on 5.10 by windows defender

### ISSUE THREAD

**Issue by Fanatiikon** [kangyu-california/PersistentWindows#69] opened 2020-12-22 19:03 UTC
For some reason the new 5.10 version is instantly detected as a virus and deleted by windows defender (just the .exe file). As such I am not able to upgrade as of yet since it would mean using my PC with windows defender deactivated.

**Comment by kangyu-california** [comment] 2020-12-22 20:19
Not reproducible on my machines.
Please post a snapshot of your defender report.

**Comment by kangyu-california** [comment] 2020-12-22 21:07
It is known that defender would block running PW for first time running due to unknown app, just select run it anyway.
![image](https://user-images.githubusercontent.com/59128756/102932853-f77ceb00-4455-11eb-91ce-c8ed2605e82c.png)

Preliminary conclusion: There is no virus detected in .exe file unzipped from 5.10 release.

**Comment by Fanatiikon** [comment] 2020-12-23 01:36
I had deleted it earlier today and now it normally started with no windows defender error. I've attacked the screenshots of the windows defender error. What i did by mistake the first time around was make a copy of the archive and then unarchived it(by mistake fyi). I haven't yet checked if that was what caused it so i can't say for sure but i'm glad it works now.
 
![image](https://user-images.githubusercontent.com/76494177/102948876-91cd4500-44cf-11eb-9f4b-2d090a782b2c.png)
![image](https://user-images.githubusercontent.com/76494177/102948907-a7426f00-44cf-11eb-8626-36ba1a1ca251.png)
![image](https://user-images.githubusercontent.com/76494177/102948913-aad5f600-44cf-11eb-9930-03942eaf739d.png)
![image](https://user-images.githubusercontent.com/76494177/102948922-af9aaa00-44cf-11eb-8e5c-6e09c1bb33db.png)
![image](https://user-images.githubusercontent.com/76494177/102948932-b6292180-44cf-11eb-9c58-e84794ecf360.png)
![image](https://user-images.githubusercontent.com/76494177/102948939-b9241200-44cf-11eb-83b4-46841b107ae5.png)

**Comment by kangyu-california** [comment] 2020-12-23 02:18
Not sure what happened to your computer.

Closing as not reproducible

**Closed** 2020-12-23 02:19 UTC
