### ISSUE TITLE
Notification spam upon window restore

### ISSUE THREAD

**Issue by jmorgannz** [kangyu-california/PersistentWindows#22] opened 2020-06-30 23:48 UTC
Hi,
This is not a high priority issue - might not even call it an issue at all; 
Thought I would log it anyway.

When PersistentWindows detects that it needs to restore the window setup, and begins doing so; it appears to fire a UI notification for each window that it restores.
This in turn fires a windows notification sound for each window as it is restored.

Would be great if there was a *single* notification which started out saying *restoring windows*, then changed to *done* when complete, then disappeared.

As it is currently, if you have your speakers turned up you get spammed with many sequential notification sounds each time you restore monitor setup.

**Comment by kangyu-california** [comment] 2020-07-01 17:24
Hi,

The issue is scheduled to be fixed by next release 4.24 by this weekend

**Comment by kangyu-california** [comment] 2020-07-04 19:02
Please try 4.24

**Closed by kangyu-california** 2020-07-04 19:02 UTC
