### ISSUE TITLE
Multiple Browser Windows (APPs/ Shortcuts/ and normal tabs) and Autostart

### ISSUE THREAD

**Issue by ant0nwax** [kangyu-california/PersistentWindows#119] opened 2021-06-08 05:17 UTC
Dear Developers

first of all Thank YOU, this tool is amazing already now
I am using Windows 10 Pro/Enterprise on a Windows VM (Remote Desktop) with a Multi Screen setup
2 x WQHD and 2 x FullHD Touchscreens = 4 Screens
Persistant Windows is running on the VM (Remote Desktop)
**This Features are mandatory for a world starting to get based on APPs running inside the Browser**

Wish 1)
_Steps tp Reproduce:_
- Restart Windows OS

_Result:_
- Persistent Windows **does not start** automagically

_Expected Result:_
- Persistent Windows is started automagically :)

Wish 2)
_Steps to Reproduce:_
- Start Persistent Windows
- Multiple Browser (Chrome) Windows are open with different URLs on different screens, with different positions, some are open inside the Browser, some are installed as APPs (Shortcuts) and have an own Icon on the Taskbar
- Use the function "Capture windows to disk"
- Restart Windows OS
- Start Persistent Windows
- Restore windows from disk

_Result:_
- Only One Browser Window (Chrome) is restored, all the others I need to launch manually AND place them manually

_Expected Result:_
- All Browser Windows (Chrome) are restored

This documentation can be adapted to all other Browsers too

Thanks for some heads up

**Comment by kangyu-california** [comment] 2021-06-08 23:42
Issue 1. PW can be auto launched at power up using task scheduler, please refer to ReadMe for details.

Issue 2. 
Usually browser app needs only be launched once as the app can restore multiple windows by itself.
Therefore PW is restricted to launch browser app only once to avoid restoring too many windows.

While I am trying to optimize the restriction, please note that Restore from DB can be invoked multiple times in order to restore multiple chrome windows. There is no need to manually launch app to restore missing window.

**Comment by ant0nwax** [comment] 2021-06-09 03:14
Good day


1)
thanks for reply, will read and integrate


2)
used case was described not exactly:

before last reboot browser could have been used differently so browser
restore works only if you never close your tabs (not my wY of working)

after reboot we would be able to restore a whole setup that is captured to
disk one month ago, a snapshot that is our default working environment

i agree its difficult to deal with the restore feature of the browser if
turned on, i think we turned it off by default, maybe thats the issue

- does the browser has a capture to disk or capture all screens setup? no
it just restores but on random screens and apps are restored as tabs...

- it does not work well, if you are curious i could record a screen
recording for all 4 screens if you are curious.


Kind Regards From Phoneland

**Comment by kangyu-california** [comment] 2021-06-19 19:04
The issue is addressed in pre-release 5.25

**Comment by ant0nwax** [comment] 2021-06-20 06:28
Thank you, looking forward to see if its working

i bet not even Chrome Restore can restore the APP/Shoetcut windows

**Closed** 2021-07-10 21:41 UTC

**Comment by ant0nwax** [comment] 2021-07-11 01:51
Hi

as i mentioned the app shortcuts are not managed by chrome restore itself and also not by persistent windows
it seems now that at least the app shortcuts are not restored anymore by persistent windows

ps: shall i open a new topic for that after a reboot on a VM the persistent windows does not appear in the tray, and so with a mouse i cannot restore from disk?

**Comment by kangyu-california** [comment] 2021-07-11 03:05
The capability to restore windows from disk is a bonus feature of PW. Due to lack of API support, it is common understanding there is no guarantee that the feature would work for all cases. ultimately it is chrome browser or Windows OS's responsibility to restore them.

The missing of PW icon on taskbar upon PC reboot from upgrade is also a known issue (I have documented this issue in Readme). PW is actually running, but somehow Windows refuse to display the icon. Reboot PC a second time usually fixes it.

**Comment by ant0nwax** [comment] 2021-07-11 05:58
But without autostart in task scheduler the icon topic was never a problem

i will try to launch the following schedule

- on logon launch Persistent Windows
- wait 42 seconds
- kill Persistent Windows Task,
- wait 12 seconds
- launch Persistent Windows

or did you try already?

Kind Regards From Phoneland

**Comment by kangyu-california** [comment] 2021-07-11 06:26
Starting PW from task scheduler has been working perfectly until recent Windows upgrades broke it.
I think the bug is on Windows side.

Or you may try wrap PW inside a .bat file, with some delay like
timeout /t 30 /nobreak > NUL

Then start the .bat file from task scheduler.

**Comment by kangyu-california** [comment] 2021-07-11 06:44
PW also provide a command option
-delay_start  <seconds_to_delay_start>

It was introduced to fix issue with starting PW from startup menu

I hope that switch works for task scheduler case as well. (I have not tested that)

**Comment by ant0nwax** [comment] 2021-07-11 10:25
okay i will give ot a go since i really appreciate PW thanks so far

Kind Regards From Phoneland
