### ISSUE TITLE
Hidden window is now visible

### ISSUE THREAD

**Issue by mirij100** [kangyu-california/PersistentWindows#104] opened 2021-04-05 11:49 UTC
When I open window in the right bottom corner then concurrently show on workspace white window as you can see here:
![image](https://user-images.githubusercontent.com/41241053/113570874-87196480-9615-11eb-9e97-2943fe34b813.png)

This window is normally hidden, but  application PersistentWindows show it.
Owner of the white window is the same application as for the window in the right bottom corner.

When is this "white" window hidden then his properties are (from Microsoft Spy++):
![image](https://user-images.githubusercontent.com/41241053/113571660-15dab100-9617-11eb-9e52-418b18e56882.png)

When is this "white" window activated by PersistentWindows application then his properties are:
![image](https://user-images.githubusercontent.com/41241053/113572079-d6f92b00-9617-11eb-97eb-53fd78613640.png)
The difference is only in WS_VISIBLE flag.

**Comment by kangyu-california** [comment] 2021-04-06 07:16
The issue is not a common one, so it is hard to reproduce.

I suspect the blank window which is usually hidden or minimized has unexpectedly received a WM_ACTIVATE message, which triggers PW trying to unhide/unminimize it.

Please check for any event 9990/9999 in event viewer when this happens.

If you are able to build PW from source code, please pull the latest fix for issue #103 (2 day ago) to see if that help or not.

**Comment by mirij100** [comment] 2021-04-06 07:56
I don't know which events in event log are related to this "white" window.
Here are all exported events in range 9990-9999 from event viewer related to PW:

[All_PW_events_9990-9999.zip](https://github.com/kangyu-california/PersistentWindows/files/6262997/All_PW_events_9990-9999.zip)

**Comment by mirij100** [comment] 2021-04-06 08:03
Here are all events from PW in range 9990-9999 exported from event viewer.
I don't know which events are related to this "white" window.
Maybe it helps you to find solution?

[All_PW_events_9990-9999.zip](https://github.com/kangyu-california/PersistentWindows/files/6263042/All_PW_events_9990-9999.zip)

**Comment by kangyu-california** [comment] 2021-04-07 16:50
The issue is same as #103.
Try undocumented command switch
-offscreen_fix=0

**Comment by mirij100** [comment] 2021-04-07 17:05
Is it possible some windows (by "windows name" or "class name") remove from control? Exists for this, for example, command line parameter?

**Comment by mirij100** [comment] 2021-04-07 17:12
I tried switch -offscreen_fix=0 now, but unfortunatelly it didn't help.

**Comment by kangyu-california** [comment] 2021-04-08 02:28
The event text you provided is not related to the issue, no wonder the switch I suggested does not solve the problem.
From the screen capture I can see you have MSVC2019 installed, please try pull the latest commit (dated 3/23) which I think should have fixed the issue.

Currently I am not considering complex solutions to exclude certain window class from auto restore.

**Comment by mirij100** [comment] 2021-04-08 07:41
> The event text you provided is not related to the issue
I provided all events 9990-9999 from event log. As I mentioned, I don't know which is related to this window.


> please try pull the latest commit
Hm, it seems good, I downloaded and compiled latest source and no more "white" window. Thanks!

**Comment by kangyu-california** [comment] 2021-04-12 17:56
Fix is released in 5.21
In case the issue still exist (especially after PC sleep), run PW with -fix_unminimized_window=0

**Closed by kangyu-california** 2021-04-12 17:56 UTC
