### ISSUE TITLE
Microsoft Sticky notes

### ISSUE THREAD

**Issue by TryhardOne** [kangyu-california/PersistentWindows#137] opened 2021-12-15 17:50 UTC
#121 but different.

Since a while, notes, which are on another monitor. are only partly restored correctly.
To be exact, all but one notes are restored to their position. One is always stuck at the other screen and with the prompt "missing process with window title "Application FrameHost" "Sticky notes"".

If I move that exact sticky note near its original position and try restoring, it is positioned correctly at its original position.

**Comment by TryhardOne** [comment] 2021-12-16 15:03
edit:
windows happened to move the sticky notes on my 3rd screen, persistent windows didnt manage to find them at all for some reason.
my screens are
primary: 2560x1440
secondary: 1920x1080
tertiary: 2560x1440

**Comment by kangyu-california** [comment] 2021-12-17 00:24
In recent windows upgrades, Microsoft has further deprecated the capability of WMIC command to query the process command line of a top level window, causing failure to launch Sticky Note app (due to wrong command line).

It is hard for PW to keep pace with new Windows releases with limited internal knowledge.

In summary, restore windows from disk is approaching end of life, and I would encourage you to challenge Microsoft for similar feature.

**Comment by TryhardOne** [comment] 2021-12-17 07:26
> In recent windows upgrades, Microsoft has further deprecated the capability of WMIC command to query the process command line of a top level window, causing failure to launch Sticky Note app (due to wrong command line).
> 
> It is hard for PW to keep pace with new Windows releases with limited internal knowledge.
> 
> In summary, restore windows from disk is approaching end of life, and I would encourage PW user to challenge Microsoft for similar feature.

That's really unfortunate, your program really helped me :/ 
Thanks for making it <3

**Comment by kangyu-california** [comment] 2021-12-20 06:50
The "missing process" dialog and fail to restore window far from original location turns out to be caused by the same bug in PW due to multi-matching one DB entry to multiple windows. The bug is fixed in 5.29 (pre-release)

**Closed** 2021-12-21 01:48 UTC
