### ISSUE TITLE
Programs minimized to the taskbar are resized

### ISSUE THREAD

**Issue by mldenison** [kangyu-california/PersistentWindows#33] opened 2020-08-10 12:20 UTC
I have two Intel NUCs connected to one monitor with two HDMI inputs on the monitor.

My 8th generation NUC maintains proper windows sizing whenever I switch the monitor to my 10th generation NUC, and back.  PersistentWindows is not running on this NUC.

However, the 10th generation NUC, when switching the monitor to the 8th generation NUC and back doesn't handle programs minimized to the taskbar.  When restoring the taskbar programs, they are 1/4 screen size and positioned in the upper left part of the display.  This NUC is running PersistentWindows.  The same issue occurs when PersistentWindows is not running.

All the drivers, and BIOS, are current.

**Comment by kangyu-california** [comment] 2020-08-10 23:52
Hi,

I can partially reproduce the issue on my side, where minimized window is incorrectly restored when switching display.
A new release will be created by 8/15 to address this issue.

For now, you may mitigate the issue by selecting "Pause auto restore" before switching display, and "Resume auto restore" after switching display back.

Thanks.

**Comment by kangyu-california** [comment] 2020-08-16 00:27
The issue is fixed by Version 4.34

**Comment by mldenison** [comment] 2020-08-23 19:40
First test - Chrome, Pale Moon and Outlook 2016 on desktop

Pale Moon remained normally on desktop
Chrome 1/4 sized in upper left corner
Outlook 1/4 sized in upper left corner

Three 9990 messages:
PersistentWindows: Restore finished with 0 windows recovered for display setting  Display_Loc0x0_Res786x590
PersistentWindows: Start restoring window layout back to 8/23/2020 5:41:50 AM  for display setting isplay_Loc0x0_Res1966x1106
PersistentWindows: Restore finished with 3 windows recovered for display setting  Display_Loc0x0_Res1966x1106

Three 9999 messages:
PersistentWindows: window minimized flag is set "00170346"
PersistentWindows: Auto fix invisible window "00170346"
PersistentWindows: Last capture time 8/23/2020 3:12:26 PM is too close to  restore time 8/23/2020 3:12:27 PM

Second test - Chrome, Pale Moon and Outlook 2016 minimized to taskbar, switched monitor input, then restored all three to desktop

Pale Moon remained normally on desktop
Chrome 1/4 sized in upper left corner
Outlook 1/4 sized in upper left corner

9990 messages:
PersistentWindows: Start restoring window layout back to 8/23/2020 3:12:20 PM for display setting Display_Loc0x0_Res786x590
PersistentWindows: Restore finished with 0 windows recovered for display setting Display_Loc0x0_Res786x590
PersistentWindows: Start restoring window layout back to 8/23/2020 5:41:50 AM for display setting Display_Loc0x0_Res1966x1106
PersistentWindows: Restore finished with 3 windows recovered for display setting Display_Loc0x0_Res1966x1106

9999 messages (several seconds earlier):
PersistentWindows: window minimized flag is set "Weather-Watch.com - Index - Google Chrome"
PersistentWindows: Auto fix invisible window "Weather-Watch.com - Index - Google Chrome"

**Comment by kangyu-california** [comment] 2020-08-26 06:05
In version 4.34, when restore minimized window to desktop, the window should be restored to exactly the same location as before it was minimized. Also a 9999 event should be logged in Event Viewer for this, such as

PersistentWindows: restore minimized window "Win32 apps \| Microsoft Docs - Google Chrome"

I have little clue why your NUC 10 would behave differently.

Still I will check in a speculative improvement fix in the next 4.35 release to avoid the "Auto fix invisible window" behavior, but I don't expect it would fix your issue.

**Comment by kangyu-california** [comment] 2020-08-27 19:02
Version 4.35 is out, that is all I can do for this issue for now.

**Closed by kangyu-california** 2020-08-27 19:02 UTC
