### ISSUE TITLE
Window moves with left click

### ISSUE THREAD

**Issue by OGNetheri** [kangyu-california/PersistentWindows#262] opened 2023-10-22 09:58 UTC
After last update, if i move e.g Chrome to other monitor and the click on main monitor, Chrome moves back to main monitor. This can continue so that if I click on 2nd monitor desktop, Chrome moves there and once again clicking on main monitors desktop , Chrome moves  again back to main.  Also, program gives notification it's already running in the background stating that apparently eartlier version service or somethinh isn't removed when program were updated.

Edit: confirmed by shutting down Persistent Windows when this behaviour ends.
Edit2: also after program restart at least right away this automatic left click moving doesn't occur.

**Comment by kangyu-california** [comment] 2023-10-22 23:38
5.45 introduced a new feature called "dual position", which allows a window to switch between foreground/background positions with just one mouse click.
To suppress the feature, modify mouse click by holding shift key.
To permanently disable the feature, run PW w/ command line -foreground_background_dual_position=0

**Comment by OGNetheri** [comment] 2023-10-23 09:56
But should this new feature move the window from monitor to monitor when user, in this case me, click empty desktop after I've moved the window to other monitor? For my english foreground/background doesn't mean main monitor/second monitor? Also as a feature suggestion, as there's much of features and it seems more is coming from time to time, could we get some UI to enable and disable the features?

**Comment by kangyu-california** [comment] 2023-10-24 00:09
Per Microsoft definition, a foreground window is the window with which the user is currently working on.
therefore there is only one "foreground" window at any time.

However Windows users like you might want to define foreground window more intuitively to something like "all the windows which are fully visible (i.e not obstructed by any other window)"

I think I know what to do next to bridge the gap between those two opinions in PW.

As for the UI enhancement suggestion, There are so many command options which Users need to read the online help to understand the purpose, It is too much work to translate them into UI.

**Comment by yrogerg77** [comment] 2023-10-24 06:35
PW has worked fine up until now. This new version behavior is very irritating and I can't stand it. I will try and see if I can get the command line method to work, but I may just reinstall an older version until this random window shuffling "feature" has UI to disable. I don't understand how this feature is helpful in any way and it keeps getting triggered by accident constantly.

**Comment by OGNetheri** [comment] 2023-10-24 15:25
> Per Microsoft definition, a foreground window is the window with which the user is currently working. The implication is that there is only one "foreground" window at any time.
> 
> However Windows users like you might want to define foreground window more intuitively to something like "all the windows which are fully visible (i.e not obstructed by any other window)", there could be multiple foreground windows at the same time, especially when there are multiple monitors available to show them all.
> 
> I think I know what to do next to bridge the gap between those two opinions in PW.
> 
> As for the UI enhancement suggestion, There are so many command options which Users need to read the online help to understand the purpose, It is too much work to translate them into UI.

I do not have _any_ windows under the Chrome when I moved it to 2nd monitor and still Chrome's full screen jumped from 2nd to main and vice versa as long as I set it as a active by e.g clicking some chat input field. The command line option helped. 

However there's also this some dialog about virtual monitors and I'm not even using those. 🤔

**Comment by kangyu-california** [comment] 2023-10-24 20:01
The bug is caused by dual position feature using Microsoft standard definition of z-order (foreground/background)
I have tweaked the z-order according to real visibility, here is the latest patch to try,
https://github.com/kangyu-california/PersistentWindows/files/13126738/PersistentWindows5.45_patch1024.zip

**Comment by OGNetheri** [comment] 2023-10-24 20:18
ok, how about this "Switch to another virtaul desktop to restore windows."? I don't have virtual monitors on use? This seems to occur at least when manually  done "restore windows from disk".

**Comment by kangyu-california** [comment] 2023-10-24 20:26
The switch to another virtual desktop dialog is triggered by mismatching of UUID of current desktop. It should go away if capture to disk again to make sure the real UUID is synced to disk

**Comment by kangyu-california** [comment] 2023-10-29 23:53
Unexpected window move (when right click or double click desktop window) is fixed in 5.46

**Comment by viralhysteria** [comment] 2023-10-30 02:33
Still experiencing this issue after updating 5.46. It went away for a while yesterday when I used the patch you posted in this thread but it ended up coming back on it's own.

**Comment by kangyu-california** [comment] 2023-10-30 19:39
The window move is the result of a new feature called "dual position", which allows a window to shift from foreground position/size to previous background position/size/z-order with just one mouse click on the unoccupied desktop window.

To suppress the feature, modify mouse click by holding Ctrl Alt keys.
To permanently disable the feature, run PW w/ command line -foreground_background_dual_position=0

For more details about dual position, please refer to help web page

**Comment by kangyu-california** [comment] 2023-11-03 21:44
Apologies for insufficient test for 5.45/5.46, please try latest 5.47

**Comment by viralhysteria** [comment] 2023-11-03 22:27
issue seems to be fixed so far on my end with 5.47, thanks 👍

**Comment by kangyu-california** [comment] 2023-12-11 19:45
Fixed in 5.48.

**Closed by kangyu-california** 2023-12-11 19:45 UTC

**Comment by ChristianMalazarte** [comment] 2024-10-25 10:14
> The window move is the result of a new feature called "dual position", which allows user to restore a foreground window to its previous background position/size/z-order with just one mouse click in the blank area of desktop window.
> 
> To suppress the feature, modify mouse click by holding Ctrl Alt keys. To permanently disable the feature, run PW w/ command line -foreground_background_dual_position=0
> 
> For more details about dual position, please refer to help web page

Thank you for adding this option. I was going out of my mind thinking it was one of my other apps conflicting with PW.
