### ISSUE TITLE
5.56 menu doesn't respect the -check_upgrade=0 command line option

### ISSUE THREAD

**Issue by Hope-UwU** [kangyu-california/PersistentWindows#336] opened 2024-07-01 12:05 UTC
When I use the `-check_upgrade=0` command line option in 5.56, PersistentWindows shows `Disable upgrade notice` instead of `Enable upgrade notice`, indicating  that the upgrade check isn't disabled.
This command line option works as intended in 5.54.

**Comment by kangyu-california** [comment] 2024-07-01 15:48
The switch works as intended by preventing PW from periodically checking for upgrade. 

The menu problem you observed is only a minor issue which exists in all PW releases including 5.54, you should not lie about that.

Here is a patch in case you need it
[PersistentWindows5.56_patch1.zip](https://github.com/user-attachments/files/16056061/PersistentWindows5.56_patch1.zip)

**Comment by Hope-UwU** [comment] 2024-07-02 04:09
> The menu problem you observed is only a minor issue which exists in all PW releases including 5.54.

That's weird since I can confirm the menu is displayed differently in 5.54 and 5.56.

In my testing I only change the target in the task scheduler.

![1719892725613.png](https://github.com/kangyu-california/PersistentWindows/assets/8344037/f64bae46-a80f-4205-8f27-2ac440f78138)

![1719892725267.png](https://github.com/kangyu-california/PersistentWindows/assets/8344037/5ff01c3c-032e-46d4-8b82-79d70b485ad6)

**Comment by kangyu-california** [comment] 2024-07-02 05:09
You are right ,the issue was actually introduced in 5.56 only by a code refactoring commit thought to be harmless.
![image](https://github.com/kangyu-california/PersistentWindows/assets/59128756/4294b9a1-16eb-45dd-ad5a-51482371c19e)

Luckily the commit only affect the initial status of the menu itself. I would say it is pretty safe to go ahead and deploy 5.56

**Comment by kangyu-california** [comment] 2024-07-14 19:07
Fixed in 5.57

**Closed by kangyu-california** 2024-07-14 19:07 UTC
