### ISSUE TITLE
Multiple Monitors not restored properly

### ISSUE THREAD

**Issue by jimboca** [kangyu-california/PersistentWindows#19] opened 2020-05-21 16:20 UTC
Hi, I've been using this for a few months and it has worked great with my previous setup.  I always use with the laptop open and I used to just have one external monitor at home, and two at work and windows were always restored properly.  But now I have 2 27" monitors at home, and the 2 24" monitors at work.   I was running an older version, but upgraded to 4.5 yesterday and ran a "Capture windows to disk" after upgrading while at work.  Then at home last night the windows were restored properly, but this morning when it restored windows at work they all just stay on the main laptop screen?

**Comment by kangyu-california** [comment] 2020-05-21 16:29
try restore window from disk
Or
Close laptop lid to sleep and reopen tehe lid to wake it up

I will investigate the issue, thx

**Comment by jimboca** [comment] 2020-05-21 16:33
Thanks, I did 'restore window from disk' at work and nothing changed.  Don't want to try it again cause all are moved the their desired location :)

**Comment by jimboca** [comment] 2020-05-22 01:21
FYI, it worked great when I hooked it up at home, the please wait message came up and all the windows were moved from the laptop back top where they were when I left work.  Ideally it would keep the same positions for all a work and home even though they are different size monitors I want them all restored to the same places?  I won't be back in the office for a few weeks so won't be able to test but appreciate you taking a look.

**Comment by kangyu-california** [comment] 2020-05-24 19:43
The issue could be caused by a flaw in the code to recognize equivalent monitor setup.
This could explain why restore from disk has no effect.

Here equivalent monitor setup means each monitor at home has same resolution as its correspondent in office, also multiple monitors must have same relative location.

The flaw has been speculatively fixed in latest version 4.6, I am closing the issue now. 

Please reopen the issue if it is not fixed by 4.6

**Comment by jimboca** [comment] 2020-05-24 21:30
Thank you! The monitors have different size and resolution but I will report back once I return to the office.

**Comment by kangyu-california** [comment] 2020-05-24 23:17
If office and home monitors have different resolutions, they will be treated as two independent display configurations, each configuration manages its own set of window positions.

It is expected for windows to move abnormally when a brand new display configuration is encountered for the first time, because there is no previous data to recover from.

**Comment by jimboca** [comment] 2020-05-25 01:03
That will work for me, thanks again.

**Comment by jimboca** [comment] 2020-06-16 00:22
Finally was back in the office today, then came home and windows were restored where they were this morning.  Thank you!

**Comment by jimboca** [comment] 2020-06-16 15:56
Can you re-open this?  I still have the problem.  When I got to work the windows remained on the laptop screen, not the 2 external monitors.  After logging in I saw the restoring windows... popup, but they didn't move, then I manually selected restore windows from disk and nothing happened.

Please let me know how I can help debug this.

**Comment by kangyu-california** [comment] 2020-06-16 18:44
Are you using Version 4.6?
The failure to restore from disk sounds like a bug that was fixed in Version 4.10
Please try latest version.
If V4.10 still does not solve your problem, please let me know more details about your office monitor configuration,
For example, 
are the monitors using Display Port or HDMI? 
do you power on monitor first before wake up the laptop
etc

**Comment by jimboca** [comment] 2020-06-16 20:04
Yes, I upgraded to 4.10 a few days ago.

Both home and work use the same Dell Dock WD19 which is connected to the Laptop USB C, and the monitors are connected do the Display Port outputs of the Dock.  

The work monitors Dell P2311H max resolution 1920x1080 and use a Display Port to DVI conversion cable

The home monitors are Dell 27" Class 4K IPS Monitor (don't have model number handy) but are using the highest resolution and connected with Display Port.

The monitors always wake up when I wake up the laptop, but don't actually display anything until I log in, and they are displaying windows backgrounds when the 'restoring' message pops up.

**Comment by kangyu-california** [comment] 2020-06-16 21:02
I suspect the required display change event is not reliably triggered at office, probably due to the extra DP-DVI converter.
One remedy you can try now is to power off the office monitors, and then power them back on again. This should trigger the restore process.

One more place to look at,, open "event viewer", in "Windows Logs"  category "Appllication" section, please watch for "Error" event  (with red alert  icon) that happened this morning (the time when you dock the laptop), 
If there are such event (application error related to PersistentWindows), please paste its content.

**Comment by jimboca** [comment] 2020-06-16 21:21
I tried power off monitors and power back on and that didn't trigger an event.

I looked thru the Event Viewer -> Application section and do not see any Errors that are related to PersistentWindows.

I just tried putting laptop to sleep, disconnect from dock, then bring it back up and login and  I see the 'restoring windows' popup.  Then put it back to sleep, plugged into dock and login and I do not see the 'restoring windows' popup?  I know this used to work from when I only had one monitor at home it worked perfectly between work, home, and no dock setups.

**Comment by kangyu-california** [comment] 2020-06-16 21:57
Since Dell docks are used both at home and at office, and only the office setup has issue. My guess is the DisplayPort to DVI converter at office introduced some unknown factor that prevented restore.

One more workaround to try is to redock laptop after login, this may help to avoid interference between login event and display change event.

If that still does not work, I would suggest hook monitor directly to display port, without the DP -> DVI converter.

**Comment by kangyu-california** [comment] 2020-06-16 22:06
As a last resort, you can alway restore from disk, just don't forget to "Capture windows to disk" at office, each display configuration has its own entry in the database on disk, therefore you need to manually capture to disk for each display configuration.

**Comment by jimboca** [comment] 2020-06-16 22:46
Ok, it's just strange that when I've had the same setup at work for a while, and the only thing that has changed is going from one to two monitors at home.  I will try your workarounds...

**Comment by kangyu-california** [comment] 2020-06-16 23:10
I will enhance the utility by writing important events to system log , so that user can check them in event viewer. This will help to diagnose issues.

A new release will be created by the end of this week. Thanks for the feedback.

**Comment by jimboca** [comment] 2020-06-16 23:47
That sounds like a great feature!

**Comment by jimboca** [comment] 2020-06-17 17:23
So I did a Capture to disk before leaving last night, then after logging in and seeing no windows move I did restore from disk and nothing happens?

**Comment by kangyu-california** [comment] 2020-06-17 20:20
So now we have confirmed two failures:
1. automatic restore failure
2. save/restore from disk failure

I have figured out how to fix the first failure, currently I am working on it.

**Comment by kangyu-california** [comment] 2020-06-19 00:50
V4.11 is released, which should have fixed issue 1 (automatic restore failure)

Also capture/restore events are printed to event log under "Windows Logs" / "Application" category, search for event id 9990 for general information and event id 9999 for exception errors. Switch to detailed view to see the message.

**Comment by jimboca** [comment] 2020-06-19 16:11
Much appreciated, I have it installed and will test.

**Comment by jimboca** [comment] 2020-06-19 22:05
I put the laptop to sleep, disconnect usb-c to dock, brought it back up so all windows were on main laptop display.

I see the 2 events:

```
 <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application" /> 
  <EventID Qualifiers="0">9990</EventID> 
  <Level>4</Level> 
  <Task>0</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2020-06-19T21:48:10.379185000Z" /> 
  <EventRecordID>37554</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>redacted</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>Mark final window position at 6/19/2020 2:48:10 PM for display setting Display_Loc0x0_Res2194x1234</Data> 
  </EventData>
  </Event>
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application" /> 
  <EventID Qualifiers="0">9990</EventID> 
  <Level>4</Level> 
  <Task>0</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2020-06-19T21:48:02.261694400Z" /> 
  <EventRecordID>37553</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>redacted</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>Restore finished for display setting Display_Loc0x0_Res2194x1234</Data> 
  </EventData>
  </Event>
```

Then I plug usb-c back into the dock and open the laptop and login and the 14 or so windows don't move back to where they were on the 2 screens connected to the dock. I see the events:

```
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application" /> 
  <EventID Qualifiers="0">9990</EventID> 
  <Level>4</Level> 
  <Task>0</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2020-06-19T21:49:36.800225000Z" /> 
  <EventRecordID>37563</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>redacted</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>Restore finished for display setting Display_Loc-11x-1080_Res1920x1080__Display_Loc0x0_Res2194x1234__Display_Loc1909x-1090_Res1920x1080</Data> 
  </EventData>
  </Event>

- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application" /> 
  <EventID Qualifiers="0">9990</EventID> 
  <Level>4</Level> 
  <Task>0</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2020-06-19T21:49:31.210612300Z" /> 
  <EventRecordID>37562</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>redacted</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>Restore window position to 6/19/2020 2:49:31 PM for display setting Display_Loc-11x-1080_Res1920x1080__Display_Loc0x0_Res2194x1234__Display_Loc1909x-1090_Res1920x1080</Data> 
  </EventData>
  </Event>

- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application" /> 
  <EventID Qualifiers="0">9990</EventID> 
  <Level>4</Level> 
  <Task>0</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2020-06-19T21:49:30.709145300Z" /> 
  <EventRecordID>37561</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>redacted</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>Restore finished for display setting Display_Loc0x0_Res2194x1234</Data> 
  </EventData>
  </Event>
```

**Comment by kangyu-california** [comment] 2020-06-19 23:30
Thanks for the feedback, from which I found bug causing issue (2) fail to manual save/restore from disk due to negative monitor coordinate.
This issue has been fixed in latest 4.12

I am still working on root cause issue 1 (automatic restore fail)

**Comment by jimboca** [comment] 2020-06-20 00:01
Awesome thank you. I won't be back in the office for 2 weeks so will try when I return.

**Comment by kangyu-california** [comment] 2020-06-27 23:08
Just released 4.23 addressing the potential miscapture bug.

**Comment by jimboca** [comment] 2020-06-28 05:52
Thanks!

**Comment by kangyu-california** [comment] 2020-07-05 00:26
Please try 4.25, which further reduces the chance of miscapture.
Reopen the issue if the latest version still does not work

**Closed by kangyu-california** 2020-07-05 00:26 UTC

**Comment by jimboca** [comment] 2020-07-05 00:32
Thanks! Back in the office Monday so will be able to test.

**Comment by jimboca** [comment] 2020-07-07 20:07
I know this is closed, but just wanted to say thank you again, working perfectly now when I return to work with my setup here.  Much appreciated!
