### ISSUE TITLE
(CTRL + Minimize) Restored windows always have wrong scaling on dual monitor

### ISSUE THREAD

**Issue by AgentKazy** [kangyu-california/PersistentWindows#361] opened 2024-10-16 14:25 UTC
Hi, when restoring windows from CTRL + Minimize, (~~all~~ not all windows, but those that are affected happens every time) the restored windows have the wrong display scaling (and a border sometimes bleeds into the main window, for example in white as shown on the "After restore" screenshot below).

I'm guessing this is due to having two monitors with different resolutions and display scales. Screenshots of the display settings for both monitors and the issue itself below.

The current workaround is dragging the second monitor's window out of fullscreen and back into fullscreen to render at the correct display scale.

Using: Windows 10 Pro 22H2 build 19045.4412 | PersistentWindows 5.59.9025.28524

Display 1
![Display 1](https://github.com/user-attachments/assets/103af446-0c78-4d4d-bed7-690bff642718)

Display 2
![Display 2](https://github.com/user-attachments/assets/36e6894e-ac68-49c0-b07f-7b04a63d2672)

Before minimizing
![1 Before](https://github.com/user-attachments/assets/2b58293f-992a-405f-a75f-56be73a5e08f)

Minimized
![2 Minimize](https://github.com/user-attachments/assets/a36d5bc2-d6ed-4ee5-946a-455f2cd7b27f)

After restore
![3 After](https://github.com/user-attachments/assets/7129e2a7-c47e-41dd-a0aa-c711a7f576e1)

**Comment by kangyu-california** [comment] 2024-10-16 21:35
The font zoom issue is duplicate of #349, which I could not reproduce. PW is only responsible for restoring window size/location, the content drawing and font rendering is solely controlled by the underlying app itself instead of PW.

The screen border bleeding issue can be reliably reproduced, this seems to be caused by inconsistent rendering of maximized window by Windows OS, perhaps due to rounding error.  Again there is nothing can be done in PW to address this.

**Closed** 2024-11-08 16:50 UTC
