### ISSUE TITLE
Minimized programs not being auto restored

### ISSUE THREAD

**Issue by ghost** [kangyu-california/PersistentWindows#330] opened 2024-06-20 22:48 UTC
hey I'm new to using Persistent Window and I'm also having a similar issue I downloaded it today and followed all the instructions for 5.54_patch5 on Windows 10 but I noticed when I have programs minimized and the monitors came back from sleep the programs wouldn't be on the same monitor anymore its just randomly on one of the other monitors, I'm really not sure if I'm doing something wrong or if Persistent Windows doesn't support minimized programs as I've noticed if the programs are not minimized they come back were I left them just as Persistent Windows is supposed to work.

**Comment by Bannpix** [comment] 2024-06-20 22:49
For this example its Google Chrome it sometimes does work

**Comment by Bannpix** [comment] 2024-06-20 22:50
i checked One log labeled 9999

showing PersistentWindows: Restore aborted for Display

**Comment by kangyu-california** [comment] 2024-06-21 04:06
Any chance you are running 3rd party window tweaking tools? Some of them is known to cause PW unable to capture window position changes.

If that is not the case, you basically need to go through the debug procedures described in my posts in #321 to prove that the failure to restore minimized chrome window is indeed due to PW faulty behavior.

The complete diagnosis is unpleasantly time consuming, which I don't like to go through one more time. Smart user tends to single out one piece of event log and ask why,  which is totally irrelevant to the issue they experienced, and the most frustrating part is that after several rounds of experiment, it turns out the issue is expected.

**Comment by kangyu-california** [comment] 2024-06-22 00:43
Before the issue is root caused, you may use snapshot restore or restore from disk as an alternative.

**Comment by kangyu-california** [comment] 2024-06-23 03:34
The issue is caused by Windows failed to generate foreground event when a window is unminimized on non-primary monitor.

This is fixed in latest patch
[PersistentWindows5.54_patch8.zip](https://github.com/user-attachments/files/15942424/PersistentWindows5.54_patch8.zip)

**Closed** 2024-07-01 15:54 UTC
