### ISSUE TITLE
Re-arranged windows always remain on top

### ISSUE THREAD

**Issue by anenviousguest** [kangyu-california/PersistentWindows#55] opened 2020-10-30 07:29 UTC
Hi,

I noticed with the latest 5.0 release that the windows somehow get sticky 'on top' attribute (don't know the exact term).

How it manifested itself:
* I got my windows re-arranged by the app.
* Now if I try to switch (with Alt-Tab or mouse) from an active window to some other one, the window where I wanted to switch to doesn't appear because the current app remain on top.

This is the bug specific to the latest 5.0 release, before that it used to work fine.

Would be awesome if you could take a look.

**Comment by JohnChristmann** [comment] 2020-10-30 18:45
I noticed this for the first time today, on just two windows but not the rest.  It usually does not do this.

**Comment by kangyu-california** [comment] 2020-10-30 19:33
fix window z-order was turned on by default in release 5.0 to fully support snapshot feature

z-order fix can be turned off by running PW 5.0 with -fix_zorder=0
(note there is no space)

I will try to fix this issue in 5.1

**Comment by kangyu-california** [comment] 2020-11-02 02:23
PW can automatically detect wrong topmost window and fix it in real time. The issue is not reproducible on my test environment, my win10 version is latest 2004, also I usually run PW with administrator privilege, not sure if that matters or not.

Any way the issue should have been fixed by release 5.1, in which zorder fix feature is only activated when restoring snapshot by default. If user does not use snapshot feature, this issue should not occur.

**Comment by anenviousguest** [comment] 2020-11-02 07:38
1. I presume 'Restore windows from disk' menu item does exactly that - restores from the snapshot, correct?
2. If I resume my laptop from hibernate while having multiple external displays connected, I observe PW recovering the windows positions - are the snapshots used in this case as well?

**Comment by kangyu-california** [comment] 2020-11-02 19:15
snapshot is a new feature introduced since release 5.0 to address issue #42 
it is still in early stage of development, so not formally documented in readme.

If you are interested in this new feature, take a look at 5.0 release note

**Closed by kangyu-california** 2020-11-02 19:15 UTC
